import { useEffect, useRef, useState } from 'react';
import { createFileRoute, Link } from '@tanstack/react-router';
import { CheckCircle2, Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react';
import { Shell } from '@/components/shell';
import { useShop } from '@/lib/shop-store';
import { defaultSearch, LISTINGS } from '@/lib/catalog';
import { pick, showUnit, formatPrice, useUi } from '@/lib/l10n';
import { whatsappHref } from '@/lib/whatsapp';
export const Route=createFileRoute('/panier')({component:Checkout});
type Receipt={order:{id:string;status:string;subtotal:number;total:number|null;items:unknown[]};trackingToken:string|null};
function Checkout(){
 const {locale}=useUi();const ar=locale==='ar';const cart=useShop(s=>s.cart);const products=useShop(s=>s.products)??LISTINGS;const setQty=useShop(s=>s.setQuantity);const clear=useShop(s=>s.clear);
 const [name,setName]=useState('');const [phone,setPhone]=useState('');const [city,setCity]=useState('Khouribga');const [fulfilment,setFulfilment]=useState('pickup');const [address,setAddress]=useState('');const [notes,setNotes]=useState('');const [consent,setConsent]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [receipt,setReceipt]=useState<Receipt|null>(null);const [website,setWebsite]=useState('');const requestId=useRef('');
 const items=cart.map(i=>({item:products.find(p=>p.id===i.id),...i}));const subtotal=items.reduce((n,i)=>n+(i.item?.price??0)*i.quantity,0);
 useEffect(()=>{try{requestId.current=sessionStorage.getItem('khadija-checkout-key')||crypto.randomUUID();sessionStorage.setItem('khadija-checkout-key',requestId.current);const previous=sessionStorage.getItem('khadija-receipt');if(previous)setReceipt(JSON.parse(previous));}catch{requestId.current=crypto.randomUUID();}void fetch('/api/metrics',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'checkout_opened'})}).catch(()=>{});},[]);
 async function submit(e:React.FormEvent){e.preventDefault();if(!consent||busy)return;setBusy(true);setError('');try{const utm=new URLSearchParams(sessionStorage.getItem('khadija-campaign')||'');const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':requestId.current},body:JSON.stringify({items:cart,name,phone,city,fulfilment,address,notes,locale,website,source:utm.get('utm_campaign')||utm.get('utm_source')||'website'})});const data=await r.json();if(!r.ok)throw new Error(data.error);setReceipt(data);sessionStorage.setItem('khadija-receipt',JSON.stringify(data));sessionStorage.removeItem('khadija-checkout-key');clear();}catch(err){setError(ar?'تعذر تسجيل الطلب. تحققوا من المعلومات وأعيدوا المحاولة.':'Impossible d’enregistrer la demande. Vérifiez vos informations et réessayez.');}finally{setBusy(false);}}
 async function refresh(){if(!receipt?.trackingToken)return;try{const r=await fetch('/api/orders/'+receipt.order.id,{headers:{Authorization:'Bearer '+receipt.trackingToken}});if(r.ok){const d=await r.json();setReceipt({...receipt,order:d.order});}}catch{}}
 return <Shell><div className="mx-auto max-w-6xl px-4 py-7 sm:px-8">
  {receipt?<div className="checkout-panel mx-auto max-w-xl text-center"><CheckCircle2 className="mx-auto size-14 text-grove"/><h1 className="mt-4 font-display text-3xl font-semibold">{ar?'تم تسجيل طلبكم':'Votre demande est enregistrée.'}</h1><p className="mt-3 text-muted">{ar?'خديجة ستؤكد التوفر والمجموع وطريقة الاستلام.':'Khadija doit encore confirmer la disponibilité, le total et le retrait.'}</p><p className="mt-5 text-xl font-semibold" dir="ltr">{receipt.order.id}</p><p className="mt-3 order-step">{({new:ar?'في انتظار التأكيد':'À confirmer',confirmed:ar?'مؤكد':'Confirmée',preparing:ar?'قيد التحضير':'En préparation',ready:ar?'جاهز':'Prête',completed:ar?'تم التسليم':'Terminée',cancelled:ar?'ملغى':'Annulée'} as Record<string,string>)[receipt.order.status]}</p><p className="mt-4 font-semibold">{ar?'مجموع المنتجات':'Sous-total produits'}: {formatPrice(receipt.order.subtotal,locale)}</p><div className="mt-5 flex flex-wrap justify-center gap-3"><button onClick={()=>void refresh()} className="hero-secondary">{ar?'تحديث الحالة':'Actualiser le suivi'}</button><a target="_blank" rel="noopener noreferrer" className="hero-primary" href={whatsappHref(ar?`السلام عليكم خديجة، أود متابعة طلبي ${receipt.order.id}.`:`Salam Khadija, je souhaite suivre ma demande ${receipt.order.id}.`)}>WhatsApp</a></div><button className="mt-6 text-sm text-grove" onClick={()=>{setReceipt(null);sessionStorage.removeItem('khadija-receipt');requestId.current=crypto.randomUUID();}}>{ar?'تسوق من جديد':'Faire une nouvelle demande'}</button></div>:
  <><p className="hero-eyebrow">{ar?'مائدتكم تبدأ هنا':'VOTRE TABLE COMMENCE ICI'}</p><h1 className="mt-3 font-display text-4xl font-semibold">{ar?'سلة من خيرات البلاد':'Un panier de bonnes choses.'}</h1>{!cart.length?<div className="checkout-panel mt-6 text-center"><ShoppingBag className="mx-auto size-12 text-clay"/><p className="mt-4">{ar?'السلة فارغة، اكتشفوا منتجات خديجة.':'Votre panier attend vos envies.'}</p><Link to="/" search={defaultSearch} className="hero-primary mt-5">{ar?'تصفح المنتجات':'Découvrir les produits'}</Link></div>:<div className="mt-6 grid gap-6 lg:grid-cols-[1fr_1fr]">
   <section className="checkout-panel"><h2 className="font-semibold">{ar?'اختياراتكم':'Vos envies'}</h2>{items.map(({item,id,quantity})=><div key={id} className="flex items-center gap-3 border-b border-line py-5"><img src={item?.images[0]} alt="" className="size-20 rounded-xl object-cover"/><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{item?pick(item.title,locale):id}</p><p className="text-xs text-muted">{item?showUnit(item.unit,locale):''}</p><div className="mt-2 flex items-center gap-2"><button type="button" aria-label={ar?'نقص الكمية':'Diminuer'} onClick={()=>setQty(id,quantity-1)} className="grid size-9 place-items-center rounded-full border border-line"><Minus className="size-4"/></button><span>{quantity}</span><button type="button" aria-label={ar?'زد الكمية':'Augmenter'} onClick={()=>setQty(id,quantity+1)} className="grid size-9 place-items-center rounded-full border border-line"><Plus className="size-4"/></button><button type="button" aria-label={ar?'حذف':'Retirer'} onClick={()=>setQty(id,0)} className="ms-2 text-muted"><Trash2 className="size-4"/></button></div></div><span className="text-sm font-semibold">{formatPrice((item?.price??0)*quantity,locale)}</span></div>)}<div className="mt-5 flex justify-between font-semibold"><span>{ar?'مجموع المنتجات':'Sous-total'}</span><span>{formatPrice(subtotal,locale)}</span></div><p className="mt-2 text-xs leading-6 text-muted">{ar?'ثمن التوصيل والتوفر يؤكدان قبل اعتماد الطلب. لا يتم الدفع هنا.':'Frais de livraison et disponibilité à confirmer. Aucun paiement en ligne.'}</p></section>
   <form onSubmit={e=>void submit(e)} className="checkout-panel"><h2 className="font-semibold">{ar?'كيف نتواصل معكم؟':'À qui préparer ce panier ?'}</h2><div className="mt-4 grid gap-4"><label className="text-sm">{ar?'الاسم':'Votre nom'}<input required minLength={2} maxLength={80} autoComplete="name" className="checkout-field mt-1" value={name} onChange={e=>setName(e.target.value)}/></label><label className="text-sm">{ar?'رقم الهاتف':'Téléphone'}<input required type="tel" autoComplete="tel" pattern="[+0-9 ()-]{8,20}" className="checkout-field mt-1" dir="ltr" placeholder="+212 …" value={phone} onChange={e=>setPhone(e.target.value)}/></label><label className="text-sm">{ar?'المدينة':'Ville'}<input required minLength={2} maxLength={80} autoComplete="address-level2" className="checkout-field mt-1" value={city} onChange={e=>setCity(e.target.value)}/></label><fieldset><legend className="text-sm">{ar?'الاستلام':'Réception'}</legend><div className="mt-2 flex gap-3"><label className="text-sm"><input type="radio" checked={fulfilment==='pickup'} onChange={()=>setFulfilment('pickup')} name="fulfilment"/> {ar?'استلام بخريبكة':'Retrait à Khouribga'}</label><label className="text-sm"><input type="radio" checked={fulfilment==='delivery'} onChange={()=>setFulfilment('delivery')} name="fulfilment"/> {ar?'طلب توصيل':'Demander une livraison'}</label></div></fieldset>{fulfilment==='delivery'?<label className="text-sm">{ar?'عنوان التوصيل':'Adresse de livraison'}<textarea required minLength={5} maxLength={250} autoComplete="street-address" className="checkout-field mt-1" value={address} onChange={e=>setAddress(e.target.value)}/></label>:null}<label className="text-sm">{ar?'ملاحظة، حساسية أو توقيت مفضل':'Note, allergie ou horaire souhaité'}<textarea maxLength={1000} rows={3} className="checkout-field mt-1" value={notes} onChange={e=>setNotes(e.target.value)}/></label><label className="hidden" aria-hidden="true">Website<input tabIndex={-1} autoComplete="off" value={website} onChange={e=>setWebsite(e.target.value)}/></label><label className="flex items-start gap-2 text-xs leading-6 text-muted"><input type="checkbox" required checked={consent} onChange={e=>setConsent(e.target.checked)} className="mt-1"/>{ar?'أوافق على استخدام هذه المعلومات لمعالجة الطلب والتواصل معي بخصوصه.':'J’accepte l’utilisation de ces informations pour traiter ma demande et me contacter à son sujet.'}</label>{error?<p role="alert" className="text-sm text-heart">{error}</p>:null}<button type="submit" disabled={busy||!consent} className="hero-primary w-full disabled:opacity-50">{busy?(ar?'جارٍ التسجيل…':'Enregistrement…'):(ar?'أرسلوا طلبي لخديجة':'Enregistrer ma demande')}</button></div></form>
  </div>}</>}
 </div></Shell>;
}
