/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MessaggiRouteImport } from './routes/messaggi'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as SalvatiRouteImport } from './routes/salvati'
import { Route as VendiRouteImport } from './routes/vendi'
import { Route as VenditeRouteImport } from './routes/vendite'
import { Route as ListingIdRouteImport } from './routes/listing.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessaggiRoute = MessaggiRouteImport.update({
  id: '/messaggi',
  path: '/messaggi',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const SalvatiRoute = SalvatiRouteImport.update({
  id: '/salvati',
  path: '/salvati',
  getParentRoute: () => rootRouteImport,
} as any)
const VendiRoute = VendiRouteImport.update({
  id: '/vendi',
  path: '/vendi',
  getParentRoute: () => rootRouteImport,
} as any)
const VenditeRoute = VenditeRouteImport.update({
  id: '/vendite',
  path: '/vendite',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/messaggi': typeof MessaggiRoute
  '/panier': typeof PanierRoute
  '/salvati': typeof SalvatiRoute
  '/vendi': typeof VendiRoute
  '/vendite': typeof VenditeRoute
  '/listing/$id': typeof ListingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/messaggi': typeof MessaggiRoute
  '/panier': typeof PanierRoute
  '/salvati': typeof SalvatiRoute
  '/vendi': typeof VendiRoute
  '/vendite': typeof VenditeRoute
  '/listing/$id': typeof ListingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/messaggi': typeof MessaggiRoute
  '/panier': typeof PanierRoute
  '/salvati': typeof SalvatiRoute
  '/vendi': typeof VendiRoute
  '/vendite': typeof VenditeRoute
  '/listing/$id': typeof ListingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/messaggi'
    | '/panier'
    | '/salvati'
    | '/vendi'
    | '/vendite'
    | '/listing/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/messaggi'
    | '/panier'
    | '/salvati'
    | '/vendi'
    | '/vendite'
    | '/listing/$id'
  id:
    | '__root__'
    | '/'
    | '/messaggi'
    | '/panier'
    | '/salvati'
    | '/vendi'
    | '/vendite'
    | '/listing/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MessaggiRoute: typeof MessaggiRoute
  PanierRoute: typeof PanierRoute
  SalvatiRoute: typeof SalvatiRoute
  VendiRoute: typeof VendiRoute
  VenditeRoute: typeof VenditeRoute
  ListingIdRoute: typeof ListingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messaggi': {
      id: '/messaggi'
      path: '/messaggi'
      fullPath: '/messaggi'
      preLoaderRoute: typeof MessaggiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salvati': {
      id: '/salvati'
      path: '/salvati'
      fullPath: '/salvati'
      preLoaderRoute: typeof SalvatiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendi': {
      id: '/vendi'
      path: '/vendi'
      fullPath: '/vendi'
      preLoaderRoute: typeof VendiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendite': {
      id: '/vendite'
      path: '/vendite'
      fullPath: '/vendite'
      preLoaderRoute: typeof VenditeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MessaggiRoute: MessaggiRoute,
  PanierRoute: PanierRoute,
  SalvatiRoute: SalvatiRoute,
  VendiRoute: VendiRoute,
  VenditeRoute: VenditeRoute,
  ListingIdRoute: ListingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
